'use server';

/**
 * @fileOverview Generates alternative author bios using AI to allow portfolio owners to experiment with different narratives.
 *
 * - generateAuthorBioOptions - A function that generates alternative author bios.
 * - GenerateAuthorBioOptionsInput - The input type for the generateAuthorBioOptions function.
 * - GenerateAuthorBioOptionsOutput - The return type for the generateAuthorBioOptions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAuthorBioOptionsInputSchema = z.object({
  existingBio: z.string().describe('The existing author bio to generate alternatives for.'),
  numberOfOptions: z.number().default(3).describe('The number of alternative bios to generate.'),
});
export type GenerateAuthorBioOptionsInput = z.infer<typeof GenerateAuthorBioOptionsInputSchema>;

const GenerateAuthorBioOptionsOutputSchema = z.object({
  bios: z.array(z.string()).describe('An array of alternative author bios generated by AI.'),
});
export type GenerateAuthorBioOptionsOutput = z.infer<typeof GenerateAuthorBioOptionsOutputSchema>;

export async function generateAuthorBioOptions(input: GenerateAuthorBioOptionsInput): Promise<GenerateAuthorBioOptionsOutput> {
  return generateAuthorBioOptionsFlow(input);
}

const generateAuthorBioOptionsPrompt = ai.definePrompt({
  name: 'generateAuthorBioOptionsPrompt',
  input: {schema: GenerateAuthorBioOptionsInputSchema},
  output: {schema: GenerateAuthorBioOptionsOutputSchema},
  prompt: `You are a professional biography writer. Given an existing author bio, generate {{numberOfOptions}} alternative bios that are engaging and highlight the author's skills and experience.

Existing Bio: {{{existingBio}}}

Alternative Bios:
{{#each (range numberOfOptions)}}
{{@index + 1}}. {{/each}}`,
  config: {
    temperature: 0.7,
    maxOutputTokens: 500,
  },
});

const generateAuthorBioOptionsFlow = ai.defineFlow(
  {
    name: 'generateAuthorBioOptionsFlow',
    inputSchema: GenerateAuthorBioOptionsInputSchema,
    outputSchema: GenerateAuthorBioOptionsOutputSchema,
  },
  async input => {
    const {
      output: {
        bios: rawBios,
      },
    } = await generateAuthorBioOptionsPrompt(input);

    const bios = rawBios?.map(bio => {
      // Remove leading numbering from the bios
      return bio.replace(/^\d+\.\s*/, '');
    });

    return {
      bios: bios ?? [],
    };
  }
);

// Helper function for Handlebars to generate a range of numbers
Handlebars.registerHelper('range', function (count: number) {
  const result = [];
  for (let i = 0; i < count; i++) {
    result.push(i);
  }
  return result;
});

import Handlebars from 'handlebars';
